### ISSUE TITLE
Upgrade pyo3 library.

### ISSUE THREAD

**Issue by shrids** [pravega/pravega-client-rust#187]
**Problem description**
The current python bindings uses 0.11.* version of pyo3.
We should upgrade to the latest version of the pyo3 library.

**Problem location**
pyo3 version.

**Suggestions for an improvement**
Use the latest version. Migration guide: https://pyo3.rs/master/migration.html#from-011-to-012

**Comment by Tristan1900** [comment]
This is fixed by this PR https://github.com/pravega/pravega-client-rust/pull/260
