### ISSUE TITLE
Wrong scope in tablemap

### ISSUE THREAD

**Issue by Tristan1900** [pravega/pravega-client-rust#217]
**Problem description**
Tablemap is using `_table` scope from the first commit. It's not revealed to be a bug until we restrict the permission of the client. We probably want to use something like `<user scope>/_table+name/0` as the internal segment.

Update: segment name as `<user scope>/<table name>_kvtable/0`

**Problem location**
tablemap

**Suggestions for an improvement**

**Comment by tkaitchuck** [comment]
We should use the same naming conventions as Java
