### ISSUE TITLE
Prefetching segment reader panics when the caller closes the reader before reaching the end of the stream

### ISSUE THREAD

**Issue by claudiofahey** [pravega/pravega-client-rust#224]
**Problem description**
The byte stream reader panics at:
https://github.com/pravega/pravega-client-rust/blob/master/src/segment_reader.rs#L474
This appears to occur when the byte stream reader is closed before it has reached the end of the stream.

**Problem location**
https://github.com/pravega/pravega-client-rust/blob/master/src/segment_reader.rs#L474

**Suggestions for an improvement**
Here is a commit that fixed the panic. It also changes the warning message so that it doesn't dump the entire sequence of bytes.
https://github.com/claudiofahey/pravega-client-rust/compare/a0e1fb89a55ad838323907368600af61926cb3b7..780a8fd44073095dfe05e34ae3cd7bdb50ed24f3

We may also consider simply ignoring this error completely, not even logging it as it often normal behavior for a reader to not read an entire stream.

**Comment by medvedevigorek** [comment]
@Tristan1900 , can this one be resolved or there is something else pending here? Thanks

**Comment by Tristan1900** [comment]
I think this is already solved by the linked PR and we can close it.
