### ISSUE TITLE
Provide a mechanism to determine if a byte stream has been sealed

### ISSUE THREAD

**Issue by claudiofahey** [pravega/pravega-client-rust#226]
**Problem description**
There should be an API to query whether a byte stream has been sealed.

**Problem location**
byte_stream.rs

**Suggestions for an improvement**
It is often the case that one will want to know the offset at which a stream has been sealed so that the data can then be read. A convenient API would be:
`
let (final_tail_offset, sealed) = byte_stream_reader.get_tail_offset_and_sealed_flag().unwrap()
`
This could also return (current_tail_offset, false) if the stream has not been sealed.

**Comment by tkaitchuck** [comment]
I'm not really sure that belongs on the reader. We probably want a dedicated metadata API for streams which provides this sort of information.
