### ISSUE TITLE
Byte stream writer should document the atomic write guarantee

### ISSUE THREAD

**Issue by claudiofahey** [pravega/pravega-client-rust#240]
**Problem description**
The byte stream writer writes buffers less than or equal to 8 MiB atomically. However, this critical feature is not documented. It should be documented so that users can safely utilize this guarantee without worrying about breaking implementation changes in the future.

**Problem location**
byte_stream.rs `ByteStreamWriter::write`.

**Suggestions for an improvement**

Add the following, assuming that it is correct.

> If buf length is less than or equal to 8 MiB, the entire buffer will be written atomically. If buf length is greater than 8 MiB, only the first 8 MiB will be written, and it will be written atomically. In either case, the actual number of bytes written will be returned.

**Comment by tkaitchuck** [comment]
More to the point: The number of bytes written is returned. These bytes were written atomically.

**Comment by Tristan1900** [comment]
Thanks for the issue, it has been added to the Rust doc now. 
https://pravega.github.io/pravega-client-rust/doc/pravega_client/byte/struct.ByteWriter.html#atomicity
