### ISSUE TITLE
example run error for async code

### ISSUE THREAD

**Issue by tempbottle** [pravega/pravega-client-rust#246]
**Problem description**
enter the examples dir, and run:
`cargo run --example event_write_and_read`
then get some error:
 Running `~/pravega-client-rust/target/debug/examples/event_write_and_read`
thread 'main' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.'

**Problem location**
there are many async and block_on in the async main function.

**Suggestions for an improvement**
correct the async and block_on combine in sub-crate or example.

**Comment by Tristan1900** [comment]
Thanks for the report! 
The example should work now.
