### ISSUE TITLE
Accept controller URI in tcp://ip:port format

### ISSUE THREAD

**Issue by claudiofahey** [pravega/pravega-client-rust#247]
**Problem description**
`ClientConfig.controller_uri` currently requires the value to be in a format such as `1.2.3.4:9090` or `controller.example.com:443`. This is not a true URI since it is missing the schema (see https://en.wikipedia.org/wiki/Uniform_Resource_Identifier), is inconsistent with the Java API, and requires a separate parameter to enable TLS. 

**Problem location**
ClientConfig

**Suggestions for an improvement**
Accept controller_uri in formats `tcp://1.2.3.4:9090` and `tls://controller.example.com:443`. This change should be made in a backwards-compatible way.

**Comment by claudiofahey** [comment]
FYI, here is some workaround code for this:
https://github.com/pravega/gstreamer-pravega/blob/master/pravega-video/src/utils.rs#L52

**Comment by bkc** [comment]
How closely does this need to match the Java docs for `controllerURI`?

> controllerURI The controller rpc URI. This can be of 2 types 1. tcp://ip1:port1,ip2:port2,... This is used if the controller endpoints are static and can be directly accessed. 2. pravega://ip1:port1,ip2:port2,... This is used to autodiscovery the controller endpoints from an initial controller list.

* Do multiple comma separated URIs need to be supported in a single PravegaNodeUri?
* Is the pravega scheme actually used anywhere?

Presumably the Rust client does not need to support enabling tls on the controller connection distinct from segmentstore connection as is currently documented on the Java client.

**Comment by claudiofahey** [comment]
@bkc, I wasn't even aware of the ability to specify multiple addresses or the pravega scheme. My intent for this issue was just to support formats such as `tcp://1.2.3.4:9090`, `tls://controller.example.com:443`, and to continue to support `controller.example.com:443`. I don't need multiple addresses.

I don't know if the pravega scheme is used but I'm quite sure that the Rust client does not support it so you can disregard it for the purposes of this issue.

**Comment by tkaitchuck** [comment]
@bkc The Rust client does not need to precisely match the Java client, provided it's behavior is reasonable and documented.

**Comment by Tristan1900** [comment]
@claudiofahey just wondering why do we need to make it backwards-compatible? If we release a new minor version we could have breaking changes for API.

**Comment by claudiofahey** [comment]
A breaking change would require changing about 100 lines of scripts, code, and documentation, and lots of extra testing in just gstreamer. We should avoid breaking changes when possible.
