### ISSUE TITLE
create_byte_stream_writer should be async

### ISSUE THREAD

**Issue by tkaitchuck** [pravega/pravega-client-rust#254]
**Problem description**
`create scope` is a async function
`async fn create_scope(&self, scope: &Scope) -> ResultRetry<bool>;`
but `create byte stream` writer  and blocks on it
`pub fn create_byte_stream_writer(&self, segment: ScopedSegment) -> ByteStreamWriter`
and within `create_byte_stream_writer`  runtime will block on segment metadata client
causing _"Cannot start a runtime from within a runtime."_

**Problem location**
create_byte_stream_writer

**Suggestions for an improvement**
This method should probably be async.

**Comment by Tristan1900** [comment]
Thanks Tom, we can fix the `create` by making it async but I think it's not possible to use `byte_stream_writer` in async context. The `flush` right now use `block_on` to wait for events to be returned, so it is still blocking the thread. We probably need to prioritize that `async` impl for byte client.
