### ISSUE TITLE
Unable to manually mark a stopped reader as offline

### ISSUE THREAD

**Issue by Mikey032** [pravega/pravega-client-rust#257]
**Problem description**
When you don't explicitly close a reader it will be stuck forever in an online state because it's never detected as failed and there are no methods to close it without creating a reader.

Sample code:
``` python
reader_group = manager.create_reader_group(readergroup, scope, stream)
reader = reader_group.create_reader(reader)
```
thread '<unnamed>' panicked at 'Error while creating the reader: SyncError { error_msg: "add reader Reader { name: \"<reader>\" }", source: SyncUpdateError { error_msg: "Failed to add online reader Reader { name: \"reader\" }: reader already online" } }

**Problem location**
python client binding

**Suggestions for an improvement**
Implement methods to list all readers in a reader group and be able to close them by name/id.

**Comment by tkaitchuck** [comment]
This can be done but it currently involves manually creating the object, which obviously is a terrible UX.
We can add a method on the Group to do this.

**Comment by Mikey032** [comment]
That would be great👍
