### ISSUE TITLE
package metadata incompatible with current version of maturin

### ISSUE THREAD

**Issue by bkc** [pravega/pravega-client-rust#269]
**Problem description**

python bindings cannot be built due to the following error

```shell
$ maturin build --release --no-sdist --strip --manylinux off
💥 maturin failed
  Caused by: Failed to parse Cargo.toml at Cargo.toml
  Caused by: invalid type: sequence, expected a map for key `package.metadata.maturin.project-url` at line 32 column 1
```

**Problem location**
In python_binding/Cargo.toml the project-url in `[package.metadata.maturin]` uses an older style format

```toml
project-url = ["Homepage, https://pravega.github.io/pravega-client-rust/"]
```

**Suggestions for an improvement**

per https://github.com/PyO3/maturin/issues/386

changing to the following resolves the issue with maturin version 0.10.6

```toml
project-url = { homepage = "https://pravega.github.io/pravega-client-rust/" }
```

**Comment by shrids** [comment]
**Additional context**: 
The automated maturin build script uses maturin version v0.8.3
To upgrade to the latest maturin we would also need to ensure the RUST library is manylinux complaint.
