### ISSUE TITLE
Return a dedicated error (error type) when byte stream ownership loss

### ISSUE THREAD

**Issue by wxing1292** [pravega/pravega-client-rust#287]
**Problem description**
Return a dedicated error (error type) when byte stream ownership loss

current behavior: a generic error `Custom { kind: BrokenPipe, error: "conditional check failed" }` is returned which is hard to check (assertion of ownership loss)

ideal behavior: create a dedicated type for above error so caller can know to ownership loss

**Problem location**

**Suggestions for an improvement**

**Comment by Tristan1900** [comment]
Fixed by https://github.com/pravega/pravega-client-rust/pull/296
Now it returns Error type here https://github.com/pravega/pravega-client-rust/blob/master/src/error.rs#L16
