### ISSUE TITLE
Python bindings should support ByteStream APIs

### ISSUE THREAD

**Issue by shrids** [pravega/pravega-client-rust#305]
**Problem description**
ByteStreamAPIs should be supported by Python bindings for Pravega.

**Problem location**
Python Bindings

**Suggestions for an improvement**
Enable this feature.
The current python bindings support writing events in the form of byte array
```
 def write_event_bytes(self, /, event, routing_key=None) 
```

**Comment by Tristan1900** [comment]
Same as https://github.com/pravega/pravega-client-rust/issues/313
