### ISSUE TITLE
Documentation github Action is failing

### ISSUE THREAD

**Issue by shrids** [pravega/pravega-client-rust#315]
**Problem description**
Documentation github Action is failing with 
```
cp: cannot stat 'html/pravega_client.html': No such file or directory
Error: Process completed with exit code 1.
```

**Problem location**
Github actions

**Suggestions for an improvement**
Fix the issue.

**Comment by shrids** [comment]
This is being fixed by PR: 296 https://github.com/pravega/pravega-client-rust/pull/296/files#diff-d7ecc9db1d2f1f75440ba2c3e433aec8c252e9c86a6260732400737857c71d3bR42

**Comment by Tristan1900** [comment]
Fixed by above PR
