### ISSUE TITLE
StreamManager will hang in there if it cannot connect to pravega server.

### ISSUE THREAD

**Issue by Hoohaha** [pravega/pravega-client-rust#336]
**Problem description**

StreamManager will hang in there if it cannot connect to pravega server.

```
stream_manager=pravega_client.StreamManager("tcp://127.0.0.1:9090", False, False)
```

**Problem location**

**Suggestions for an improvement**

Suggest to add timeout option to control this behaviour

**Comment by shrids** [comment]
Hi, I tried to simulate it with the latest version of client 
```python
mgr=pravega_client.StreamManager("127.0.0.1:9090", False, False, False);
```
I do not observe any blocking behaviour. Could you please try it with the latest version and let us know?

**Comment by Hoohaha** [comment]
Hi @shrids ,

The streamManager is not blocking now, but how can i know it is connected. It returned a valid streamManager object. 
And seems there no attribute to get the state of connection.

I think it should raise an exception or return a None type.
 
`StreamManager(Controller ip: "10.2.2.1:9090" ClientConfig: ClientConfig { max_connections_in_pool: 4294967295, max_controller_connections: 3, connection_type: Tokio, retry_policy: RetryWithBackoff { current: 1, base: 10, max_delay: Some(10s) }, controller_uri: PravegaNodeUri("10.2.2.1:9090"), transaction_timeout_time: 90000, mock: false, is_tls_enabled: false, disable_cert_verification: false, trustcerts: [], credentials: Credentials { inner: Basic { method: "Basic", token: "Og==" } }, is_auth_enabled: false, reader_wrapper_buffer_size: 1048576, request_timeout: 30s })
`

**Comment by shrids** [comment]
Yes, The stream manager does not create a connection. It lazily establishes a connection on when the next APIs are invoked.

**Comment by shrids** [comment]
Closing this based on the previous comment.
