### ISSUE TITLE
Publish new version of Python Bindings

### ISSUE THREAD

**Issue by maddisondavid** [pravega/pravega-client-rust#378]
**Problem description**
The last version of the Python binding published to PyPi (https://pypi.org/project/pravega/) was version 0.3.1.  This version is quite old, from 12th November 2021 and does not include many new improvements added since that date.

**Suggestions for an improvement**
Release a new version of the Python binding.

**Comment by qian1166** [comment]
There is a security issue on JIRA which needs to update python 3.9.13 to 3.10.5 may related to this issue. I tried to deploy the Dockerfile locally but end up with the following error. 
![image](https://user-images.githubusercontent.com/78283846/185938159-7f22d409-294f-4b2d-8010-5bd749d202d9.png)

**Comment by thekingofcity** [comment]
> There is a security related issue which needs to update python 3.9.13 to 3.10.5 end up with the following error when I tried to deploy the Dockerfile locally. ![image](https://user-images.githubusercontent.com/78283846/185938159-7f22d409-294f-4b2d-8010-5bd749d202d9.png)

Do you mean you will see the error if you upgrade python from 3.9.13 to 3.10.5? The python client now only supports 3.6-3.9, we may add 3.10 as well.
